SCREEN_SIZE_X = 1280
SCREEN_SIZE_Y = 720
SCREEN_RANGE_X = (0..1080)
SCREEN_RANGE_Y = (0..700)

SPRITE_PATH = 'sprites/misc/simple-mood-16x16.png'


RIGHT_ALIGNED_ENUM = 0
CENTERED_ENUM = 1
LEFT_ALIGNED_ENUM = 2

# DEFAULT_CELL_SIZE = 16 
# GRID_LIMIT_X = SCREEN_SIZE_X / DEFAULT_CELL_SIZE
# GRID_LIMIT_Y = SCREEN_SIZE_Y / DEFAULT_CELL_SIZE
